/* Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
Disk 3 moves to Rod 1
Disk 1 moves to Rod 0
Disk 2 moves to Rod 1
Disk 1 moves to Rod 1
Disk 4 moves to Rod 2
Disk 1 moves to Rod 2
Disk 2 moves to Rod 0
Disk 1 moves to Rod 0
Disk 3 moves to Rod 2
Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
Disk 5 moves to Rod 1
Disk 1 moves to Rod 0
Disk 2 moves to Rod 1
Disk 1 moves to Rod 1
Disk 3 moves to Rod 0
Disk 1 moves to Rod 2
Disk 2 moves to Rod 0
Disk 1 moves to Rod 0
Disk 4 moves to Rod 1
Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
Disk 3 moves to Rod 1
Disk 1 moves to Rod 0
Disk 2 moves to Rod 1
Disk 1 moves to Rod 1
Disk 6 moves to Rod 2
Disk 1 moves to Rod 2
Disk 2 moves to Rod 0
Disk 1 moves to Rod 0
Disk 3 moves to Rod 2
Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
Disk 4 moves to Rod 0
Disk 1 moves to Rod 0
Disk 2 moves to Rod 1
Disk 1 moves to Rod 1
Disk 3 moves to Rod 0
Disk 1 moves to Rod 2
Disk 2 moves to Rod 0
Disk 1 moves to Rod 0
Disk 5 moves to Rod 2
Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
Disk 3 moves to Rod 1
Disk 1 moves to Rod 0
Disk 2 moves to Rod 1
Disk 1 moves to Rod 1
Disk 4 moves to Rod 2
Disk 1 moves to Rod 2
Disk 2 moves to Rod 0
Disk 1 moves to Rod 0
Disk 3 moves to Rod 2
Disk 1 moves to Rod 1
Disk 2 moves to Rod 2
Disk 1 moves to Rod 2
*/